[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'
on_ft = ['php']

[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_ft = ['ruby']
