[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_show_hidden = 1
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*.jpg
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store'
'''

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_sign_column_always = 1
let g:ale_linters = {
\   'ruby': ['rubocop'],
\   'php': ['phpcs'],
\   'javascript': ['standard'],
\   'go': ['gometalinter', 'gofmt'],
\   'css': ['stylelint'],
\   'scss': ['stylelint']
\}
let g:ale_fixers = {
\   'javascript': ['standard'],
\   'go': ['gofmt']
\}
let g:ale_php_phpcs_standard = 'PSR2'
let g:ale_go_gometalinter_options = '--fast'
'''
