[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-neosnippet.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_set_highlights = 0
let g:ale_lint_on_enter = 0
let g:ale_sign_column_always = 1
let g:ale_sign_error = "X"
let g:ale_sign_warning = "!"
let g:ale_linters = {
\   'ruby': ['rubocop'],
\   'php': ['phpcs'],
\   'javascript': ['standard'],
\   'go': ['gometalinter', 'gofmt'],
\   'css': ['stylelint'],
\   'scss': ['stylelint']
\}
let g:ale_fixers = {
\   'ruby': ['rubocop'],
\   'javascript': ['prettier_standard'],
\   'go': ['gofmt']
\}
let g:ale_php_phpcs_standard = 'PSR2'
let g:ale_go_gometalinter_options = '--fast'
'''
